# Configure True Colors

set -g default-terminal "screen-256color"
set -g @catppuccin_flavour 'frappe' # or frappe, macchiato, mocha
set -g @catppuccin_window_tabs_enabled on # or off to disable window_tabs
set -g @catppuccin_user "on"
set -ogq @catppuccin_status_fill "icon"
set -g @catppuccin_window_status_style "basic" # basic, rounded, slanted, custom, or none
# Set background for the status bar
set -g @catppuccin_window_right_separator "#[fg=#313244,bg=#181825]█ "
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_left_separator "#[bg=#181825] █" 
set -g @catppuccin_window_current_fill "number"

set -ogq @catppuccin_window_flags_icon_last " 󰖰" # -
set -ogq @catppuccin_window_flags_icon_current " 󰖯" # *
set -ogq @catppuccin_window_flags_icon_zoom " 󰁌" # Z
set -ogq @catppuccin_window_flags_icon_mark " 󰃀" # M
set -ogq @catppuccin_window_flags_icon_silent " 󰂛" # ~
set -ogq @catppuccin_window_flags_icon_activity " 󱅫" # #
set -ogq @catppuccin_window_flags_icon_bell " 󰂞" # !
# Status line options
#jset -ogq @catppuccin_status_left_separator ""
set -ogq @catppuccin_status_middle_separator ""
set -ogq @catppuccin_status_connect_separator "yes" # yes, no
set -ogq @catppuccin_status_module_bg_color "#{@thm_surface_0}"


# other stuff
set -g @catppuccin_status_left_separator_inverse "no"
set -g @catppuccin_status_fill "all"

# Change Default TMUX Prefix
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Change keybinds for splitting windows vertical and horizontal 
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

# easy refreshing
unbind r
bind r source-file ~/.tmux.conf

# resize tmux panels
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# maximized and minimized tmux panels
bind -r m resize-pane -Z

# use mouse to resizing
set -g mouse on

# copy mode with vim
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse


# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator' # for navigating panes and vim/nvim with Ctrl-hjkl
set -g @plugin 'catppuccin/tmux'

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
